//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Shadow.rc
//
#define IDS_NEW_MENU                    1
#define IDS_FILE_LOAD                   2
#define IDS_FILE_SAVE                   3
#define IDC_SELECT_BY_COLOR             3
#define IDC_LIST_ALL                    3
#define IDS_NEW_FONT                    4
#define IDC_LIST_NONE                   4
#define IDS_FILE_SAVE_NEW               5
#define IDC_LIST_INVERT                 5
#define IDS_ABOUT                       6
#define IDC_SELECT_ALL                  6
#define IDC_SELECT_NONE                 7
#define IDC_SELECT_INVERT               8
#define IDS_FILE_NEW                    9
#define IDS_APP_VERSION                 10
#define IDC_GROUPBUTTON                 11
#define IDS_APP_TITLE                   11
#define IDS_APP_NAME                    12
#define IDC_TOOL_MOVE                   14
#define IDC_TOOL_NONE                   15
#define IDR_MAIN_MENU                   103
#define IDI_SHADOW                      106
#define IDD_ABOUT                       133
#define IDD_MAIN                        148
#define IDD_MAINTAB                     152
#define IDD_CREATE_SPHERE               154
#define IDD_CREATE_GEOMETRY             155
#define IDD_OBJECT_TRANSFORMS           156
#define IDD_OPTIONS_VIEWS               157
#define IDD_MODIFIER_SELECT             158
#define IDD_OBJECT_INFO                 159
#define IDD_OBJECT_COLOR                160
#define IDD_VIEWBAR                     161
#define IDD_VIEWTOOLBAR                 161
#define IDD_ANIMTOOLBAR                 161
#define IDD_MAINTOOLBAR                 162
#define IDD_BOTTOMTOOLBAR               163
#define IDC_TOOL_ROTATE                 163
#define IDC_TOOL_ZOOM                   164
#define IDD_CREATE_PLANE                164
#define IDC_TOOL_SELECT                 165
#define IDD_SMOOTHING_GROUPS            165
#define IDC_TOOL_ROLL                   166
#define IDC_TOOL_DRAG                   168
#define IDD_CREATE_BOX                  169
#define IDD_COMPONENT_MANAGER           170
#define IDD_SELECT                      171
#define IDC_TOOL_DOLLY                  172
#define IDC_CURSOR1                     173
#define IDB_AUTHOR                      174
#define IDB_LOGO                        175
#define IDC_TOOL_SCALE                  176
#define IDD_MATERIAL_EDITOR             177
#define IDD_CREATE_GROUPS               178
#define IDD_CREATE                      178
#define IDR_MAINACCEL                   179
#define IDC_TOOL_FOV                    180
#define IDC_TOOL_ZOOM_ALL               181
#define ID_STATUS_BAR                   542
#define ID_TOOL_BAR                     543
#define IDC_TAB_CREATE                  1062
#define IDC_TAB_MODIFY                  1063
#define IDC_TAB_MOTION                  1065
#define IDC_TAB_UTILITY                 1066
#define IDC_TAB_DISPLAY                 1067
#define IDC_MAINSCROLLBAR               1068
#define IDC_CREATE_SELECT_BOX           1087
#define IDC_CREATE_BOX                  1087
#define IDC_CREATE_SELECT_SPHERE        1088
#define IDC_CREATE_BOX_POS_X            1088
#define IDC_OBJECT_TRANSFORMS_POS_X     1088
#define IDC_OBJECT_POS_X                1088
#define IDC_CREATE_SPHERE               1088
#define IDC_CREATE_SELECT_GEOSPHERE     1089
#define IDC_CREATE_BOX_POS_Y            1089
#define IDC_OBJECT_TRANSFORMS_POS_Y     1089
#define IDC_CREATE_GEOSPHERE            1089
#define IDC_OBJECT_TRANSFORMS_POS_Z     1090
#define IDC_OBJECT_POS_Z                1090
#define IDC_OBJECT_TRANSFORMS_ROT_X     1091
#define IDC_OBJECT_ROT_X                1091
#define IDC_OBJECT_TRANSFORMS_ROT_Y     1092
#define IDC_OBJECT_ROT_Y                1092
#define IDC_OBJECT_TRANSFORMS_ROT_Z     1093
#define IDC_CREATE_SELECT_PLANE         1093
#define IDC_OBJECT_ROT_Z                1093
#define IDC_CREATE_PLANE                1093
#define IDC_OBJECT_TRANSFORMS_SCALE_X   1094
#define IDC_CREATE_SELECT_TORUS         1094
#define IDC_OBJECT_SCALE_X              1094
#define IDC_CREATE_DATA                 1094
#define IDC_CREATE_TORUS                1094
#define IDC_OBJECT_TRANSFORMS_SCALE_Y   1095
#define IDC_CREATE_SELECT_PYRAMID       1095
#define IDC_OBJECT_SCALE_Y              1095
#define IDC_CREATE_PYRAMID              1095
#define IDC_OPTIONS_VIEWS_BITS          1096
#define IDC_OBJECT_TRANSFORMS_SCALE_Z   1096
#define IDC_CREATE_SELECT_CYLINDER      1096
#define IDC_OBJECT_SCALE_Z              1096
#define IDC_VIEW_COLOR_BITS             1096
#define IDC_CREATE_CYLINDER             1096
#define IDC_OBJECT_TRANSFORMS_ORIGIN_X  1097
#define IDC_CREATE_SELECT_TUBE          1097
#define IDC_OBJECT_ORIGIN_X             1097
#define IDC_VIEW_DEPTH_BITS             1097
#define IDC_CREATE_TUBE                 1097
#define IDC_OBJECT_TRANSFORMS_ORIGIN_Y  1098
#define IDC_CREATE_SELECT_CONE          1098
#define IDC_OBJECT_ORIGIN_Y             1098
#define IDC_VIEW_STENCIL_BITS           1098
#define IDC_CREATE_CONE                 1098
#define IDC_OBJECT_TRANSFORMS_ORIGIN_Z  1099
#define IDC_OBJECT_ORIGIN_Z             1099
#define IDC_CREATE_BOX_DIMENSION_X      1100
#define IDC_DIMENSION_X                 1100
#define IDC_CREATE_BOX_DIMENSION_Y      1101
#define IDC_DIMENSION_Y                 1101
#define IDC_CREATE_BOX_DIMENSION_Z      1102
#define IDC_DIMENSION_Z                 1102
#define IDC_OBJECT_TRANSFORMS_POS_X_SPIN 1103
#define IDC_OBJECT_POS_X_SPIN           1103
#define IDC_OBJECT_TRANSFORMS_POS_Y_SPIN 1104
#define IDC_OBJECT_POS_Y_SPIN           1104
#define IDC_OBJECT_TRANSFORMS_POS_Z_SPIN 1105
#define IDC_OBJECT_POS_Z_SPIN           1105
#define IDC_OBJECT_TRANSFORMS_ROT_X_SPIN 1106
#define IDC_MODIFIER_TREE               1106
#define IDC_OBJECT_ROT_X_SPIN           1106
#define IDC_OBJECT_TRANSFORMS_ROT_Y_SPIN 1107
#define IDC_MODIFIER_LIST               1107
#define IDC_OBJECT_ROT_Y_SPIN           1107
#define IDC_OBJECT_TRANSFORMS_ROT_Z_SPIN 1108
#define IDC_CREATE_BOX_TASSEL_X         1108
#define IDC_TASSELLATION_X              1108
#define IDC_OBJECT_ROT_Z_SPIN           1108
#define IDC_OBJECT_TRANSFORMS_SCALE_X_SPIN 1109
#define IDC_CREATE_BOX_TASSEL_Y         1109
#define IDC_TASSELLATION_Y              1109
#define IDC_OBJECT_SCALE_X_SPIN         1109
#define IDC_OBJECT_TRANSFORMS_SCALE_Y_SPIN 1110
#define IDC_CREATE_BOX_TASSEL_Z         1110
#define IDC_TASSELLATION_Z              1110
#define IDC_OBJECT_SCALE_Y_SPIN         1110
#define IDC_OBJECT_TRANSFORMS_SCALE_Z_SPIN 1111
#define IDC_CREATE_BOX_TASSEL_X_SPIN    1111
#define IDC_OBJECT_SCALE_Z_SPIN         1111
#define IDC_OBJECT_TRANSFORMS_ORIGIN_X_SPIN 1112
#define IDC_CREATE_BOX_TASSEL_Y_SPIN    1112
#define IDC_OBJECT_ORIGIN_X_SPIN        1112
#define IDC_OBJECT_TRANSFORMS_ORIGIN_Y_SPIN 1113
#define IDC_CREATE_BOX_TASSEL_Z_SPIN    1113
#define IDC_TASSELLATION_Z_SPIN         1113
#define IDC_OBJECT_ORIGIN_Y_SPIN        1113
#define IDC_OBJECT_TRANSFORMS_ORIGIN_Z_SPIN 1114
#define IDC_OBJECT_INFO_NAME            1114
#define IDC_OBJECT_ORIGIN_Z_SPIN        1114
#define IDC_CREATE_BOX_DIMENSION_X_SPIN 1115
#define IDC_OBJECT_INFO_COLOR           1115
#define IDC_CREATE_BOX_DIMENSION_Y_SPIN 1116
#define IDC_CREATE_BOX_DIMENSION_Z_SPIN 1117
#define IDC_DIMENSION_Z_SPIN            1117
#define IDC_CREATE_BOX_CREATION_CENTER  1119
#define IDC_CREATION_CENTER             1119
#define IDC_CREATION_DATA               1120
#define IDC_START                       1120
#define IDC_PREVIOUS                    1121
#define IDC_PLAY                        1122
#define IDC_SELECT                      1122
#define IDC_NEXT                        1123
#define IDC_EDIT_MOVE                   1123
#define IDC_END                         1124
#define IDC_EDIT_ROTATE                 1124
#define IDC_KEYMODE                     1125
#define IDC_EDIT_SCALE                  1125
#define IDC_OPTIONS                     1126
#define IDC_EDIT_CENTER                 1126
#define IDC_UNDO                        1127
#define IDC_REDO                        1128
#define IDC_BIND                        1129
#define IDC_PAN                         1130
#define IDC_UNBIND                      1130
#define IDC_ROTATE                      1131
#define IDC_WARPBIND                    1131
#define IDC_FOV                         1132
#define IDC_SELECT_DIALOG               1132
#define IDC_SELECT_CROSSING             1133
#define IDC_ZOOM                        1134
#define IDC_SELECT_MODE                 1134
#define ID_OK                           1135
#define IDC_FOURVIEW                    1135
#define IDC_TRANSFORM_LOCAL             1136
#define IDC_SELECTION_LOCK              1137
#define IDC_CENTER                      1138
#define IDC_CENTER_ALL                  1139
#define IDC_ZOOM_ALL                    1140
#define IDC_TASSELLATION_X_SPIN         1142
#define IDC_TASSELLATION_Y_SPIN         1143
#define IDC_DIMENSION_X_SPIN            1144
#define IDC_DIMENSION_Y_SPIN            1145
#define IDC_SMOOTHING_GROUP_01          1146
#define IDC_SMOOTHING_GROUP_02          1147
#define IDC_SMOOTHING_GROUP_03          1148
#define IDC_SMOOTHING_GROUP_04          1149
#define IDC_SMOOTHING_GROUP_05          1150
#define IDC_SMOOTHING_GROUP_06          1151
#define IDC_SMOOTHING_GROUP_07          1152
#define IDC_SMOOTHING_GROUP_08          1153
#define IDC_SMOOTHING_AUTO              1154
#define IDC_RADIO1                      1155
#define IDC_VIEW_SHADED                 1155
#define IDC_SORT_ABC                    1155
#define IDC_VIEW_WIREFRAME              1156
#define IDC_SORT_TYPE                   1156
#define IDC_VIEW_COMPOSITE              1157
#define IDC_SORT_COLOR                  1157
#define IDC_SMOOTHING_GROUP_09          1158
#define IDC_VIEW0                       1158
#define IDC_SORT_SIZE                   1158
#define IDC_SMOOTHING_GROUP_10          1159
#define IDC_VIEW1                       1159
#define IDC_TREE1                       1159
#define IDC_SMOOTHING_GROUP_11          1160
#define IDC_VIEW2                       1160
#define IDC_LIST1                       1160
#define IDC_SMOOTHING_GROUP_12          1161
#define IDC_VIEW3                       1161
#define IDC_COMPONENT_ADD               1161
#define IDC_SMOOTHING_GROUP_13          1162
#define IDC_COMPONENT_REMOVE            1162
#define IDC_SMOOTHING_GROUP_14          1163
#define IDC_FILE_TYPE                   1163
#define IDC_SMOOTHING_GROUP_15          1164
#define IDC_FILE_LOAD                   1164
#define IDC_SMOOTHING_GROUP_16          1165
#define IDC_CHECK1                      1165
#define IDC_SMOOTHING_GROUP_17          1166
#define IDC_FILE_SAVE                   1166
#define IDC_VIEW_DISTANCE               1166
#define IDC_LIST_SHAPES                 1166
#define IDC_SMOOTHING_GROUP_18          1167
#define IDC_FILE_NEW                    1167
#define IDC_VIEW_UPDATE_ON_DIALOG_MOVE  1167
#define IDC_LIST_LIGHTS                 1167
#define IDC_SMOOTHING_GROUP_19          1168
#define IDC_LIST_CAMERAS                1168
#define IDC_SMOOTHING_GROUP_20          1169
#define IDC_TRANSFORM_X                 1169
#define IDC_LIST_HELPERS                1169
#define IDC_SMOOTHING_GROUP_21          1170
#define IDC_TRANSFORM_X_SPIN            1170
#define IDC_LIST_WARPS                  1170
#define IDC_SMOOTHING_GROUP_22          1171
#define IDC_TRANSFORM_Z                 1171
#define IDC_LIST_GROUPS                 1171
#define IDC_SMOOTHING_GROUP_23          1172
#define IDC_TRANSFORM_Z_SPIN            1172
#define IDC_MAINTOOLBAR_SELECT_TYPE     1172
#define IDC_SELECT_TYPE                 1172
#define IDC_LIST_BONES                  1172
#define IDC_SMOOTHING_GROUP_24          1173
#define IDC_TRANSFORM_Y                 1173
#define IDC_DISPLAY_SUBTREE             1173
#define IDC_COORD_SYSTEM                1173
#define IDC_SMOOTHING_GROUP_25          1174
#define IDC_TRANSFORM_Y_SPIN            1174
#define IDC_SMOOTHING_GROUP_26          1175
#define IDC_ANIMBAR_FRAME               1175
#define IDC_FRAME                       1175
#define IDC_SELECTION_SETS              1175
#define IDC_SMOOTHING_GROUP_27          1176
#define IDC_CASE_SENSITIVE              1176
#define IDC_SMOOTHING_GROUP_28          1177
#define IDC_LIST_GEOMETRY               1177
#define IDC_SMOOTHING_GROUP_29          1178
#define IDC_SMOOTHING_GROUP_30          1179
#define IDC_SELECTION_SEARCH            1179
#define IDC_SMOOTHING_GROUP_31          1180
#define IDC_SMOOTHING_GROUP_32          1181
#define IDC_SELECTION_LIST              1181
#define IDC_MATERIAL_PREVIEW            1182
#define IDC_CREATE_GEOMETRY             1183
#define IDC_CREATE_LIGHTS               1185
#define IDC_CREATE_HELPERS              1186
#define IDC_CREATE_SHAPES               1187
#define IDC_CREATE                      1200
#define IDC_ROTATE_ORIGIN               1600
#define IDC_ROTATE_FOCUS                1601
#define IDC_CENTER_EVERYTHING           1602
#define IDC_CENTER_SELECTED             1603
#define IDC_CENTER_ALL_EVERYTHING       1604
#define IDC_CENTER_ALL_SELECTED         1605
#define IDC_SELECT_RECT                 1606
#define IDC_SELECT_CIRCLE               1607
#define IDC_SELECT_POLYGON              1608
#define IDC_EDIT_USCALE                 1609
#define IDC_EDIT_NSCALE                 1610
#define IDC_EDIT_CENTER_ORIGIN          1611
#define IDC_EDIT_CENTER_SELECTION       1612
#define IDC_EDIT_CENTER_SYSTEM          1613
#define IDC_SETKEY                      8001
#define IDC_KEYMODE_AUTO                8002
#define IDC_KEYMODE_SET                 8003
#define IDM_EXIT                        40007
#define IDM_FILE_SAVE                   40009
#define IDM_FILE_LOAD                   40010
#define IDM_FILE_SAVE_NEW               40011
#define IDM_ABOUT                       40020
#define IDM_SELECT_INTERSECTING         40021
#define IDM_FILE_NEW                    40025
#define IDM_OPTIONS_VIEWS               40026
#define IDM_FILE_IMPORT                 40027
#define IDM_FILE_EXPORT                 40028

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         40029
#define _APS_NEXT_CONTROL_VALUE         1188
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
